web:
   image: web
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "81:80"
   links:
     - db
   volumes:
     - ./app:/var/www/html/

db:
  image: mariadb@sha256:490f01279be1452f12f497a592112cb960cf0500938dbf0ea3f0135cb6728d3d
  restart: always
  volumes:
    - ./database.sql:/docker-entrypoint-initdb.d/setup.sql
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: database
  ports:
    - "8889:3306"

phpmyadmin:
  image: phpmyadmin/phpmyadmin@sha256:67ba2550fd004399ab0b95b64021a88ea544011e566a9a1995180a3decb6410d
  links:
    - db
  ports:
    - 8890:80
  environment:
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: database

composer:
  image: composer/composer@sha256:d79e1a62bfecc274f6eddd9f64be151813e863fdd8572d184209eca8dd21e9fc
  ports:
    - "9001:9000"
  volumes:
    - ./app:/var/www/html/
  container_name: composer
  working_dir: /var/www/html/
  command: install

